spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    async:
      request-timeout: 3600000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tongtong.tplinkdns.com:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 123!@#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/travelclub?serverTimezone=Asia/Seoul
#    username: dk
#    password: 1234
server:
  port: 8081